// Security+ Akronyme (SY0-701)
export const PAIRS = [
  // 1. General Security Concepts
  { id: "g1", acr: "CIA", exp: "Confidentiality, Integrity, Availability", hint: "General Security Concepts", example: "The core security triad — the three properties every control aims to protect.", exampleDe: null },
  { id: "g2", acr: "AAA", exp: "Authentication, Authorization, Accounting", hint: "General Security Concepts", example: "Framework for verifying identity, granting permissions, and logging activity.", exampleDe: null },
  { id: "g3", acr: "PKI", exp: "Public Key Infrastructure", hint: "General Security Concepts", example: "System of certificates, CAs, and keys used to manage trust and encryption.", exampleDe: null },
  { id: "g4", acr: "CA", exp: "Certificate Authority", hint: "General Security Concepts", example: "Entity that issues and signs digital certificates.", exampleDe: null },
  { id: "g5", acr: "RA", exp: "Registration Authority (PKI)", hint: "General Security Concepts", example: "Verifies certificate requests before the CA issues them.", exampleDe: null },
  { id: "g6", acr: "CRL", exp: "Certificate Revocation List", hint: "General Security Concepts", example: "List of certificates that have been revoked before expiration.", exampleDe: null },
  { id: "g7", acr: "OCSP", exp: "Online Certificate Status Protocol", hint: "General Security Concepts", example: "Real-time protocol to check if a certificate is still valid.", exampleDe: null },
  { id: "g8", acr: "CSR", exp: "Certificate Signing Request", hint: "General Security Concepts", example: "Request sent to a CA to obtain a digital certificate.", exampleDe: null },
  { id: "g9", acr: "HSM", exp: "Hardware Security Module", hint: "General Security Concepts", example: "Physical device that securely generates/stores cryptographic keys.", exampleDe: null },
  { id: "g10", acr: "TPM", exp: "Trusted Platform Module", hint: "General Security Concepts", example: "Hardware chip that stores keys and supports secure boot/attestation.", exampleDe: null },
  { id: "g11", acr: "AES", exp: "Advanced Encryption Standard", hint: "General Security Concepts", example: "Symmetric block cipher, current standard for data encryption.", exampleDe: null },
  { id: "g12", acr: "DES", exp: "Data Encryption Standard", hint: "General Security Concepts", example: "Legacy symmetric cipher, considered insecure today.", exampleDe: null },
  { id: "g13", acr: "3DES", exp: "Triple DES", hint: "General Security Concepts", example: "Applies DES three times; stronger than DES but obsolete.", exampleDe: null },
  { id: "g14", acr: "RSA", exp: "Rivest-Shamir-Adleman", hint: "General Security Concepts", example: "Asymmetric encryption algorithm based on factoring large primes.", exampleDe: null },
  { id: "g15", acr: "ECC", exp: "Elliptic Curve Cryptography", hint: "General Security Concepts", example: "Asymmetric encryption using elliptic curves; efficient with smaller keys.", exampleDe: null },
  { id: "g16", acr: "DH", exp: "Diffie-Hellman", hint: "General Security Concepts", example: "Key exchange protocol allowing two parties to share a secret over an insecure channel.", exampleDe: null },
  { id: "g17", acr: "PFS", exp: "Perfect Forward Secrecy", hint: "General Security Concepts", example: "Ensures session keys aren't compromised even if long-term keys are.", exampleDe: null },
  { id: "g18", acr: "HMAC", exp: "Hash-based Message Authentication Code", hint: "General Security Concepts", example: "Combines a hash function with a secret key to verify integrity/authenticity.", exampleDe: null },
  { id: "g19", acr: "MD5", exp: "Message Digest 5", hint: "General Security Concepts", example: "Older hashing algorithm, cryptographically broken.", exampleDe: null },
  { id: "g20", acr: "SHA", exp: "Secure Hash Algorithm", hint: "General Security Concepts", example: "Family of hash functions (SHA-1, SHA-256, etc.) for integrity checks.", exampleDe: null },
  { id: "g21", acr: "PBKDF2", exp: "Password-Based Key Derivation Function 2", hint: "General Security Concepts", example: "Slows down brute-force attacks by adding computational cost to password hashing.", exampleDe: null },
  { id: "g22", acr: "GPG", exp: "GNU Privacy Guard", hint: "General Security Concepts", example: "Open-source implementation of OpenPGP for encrypting/signing data.", exampleDe: null },
  { id: "g23", acr: "PGP", exp: "Pretty Good Privacy", hint: "General Security Concepts", example: "Encryption program for signing/encrypting emails and files.", exampleDe: null },
  { id: "g24", acr: "S/MIME", exp: "Secure/Multipurpose Internet Mail Extensions", hint: "General Security Concepts", example: "Standard for encrypting and digitally signing email.", exampleDe: null },
  { id: "g25", acr: "TLS", exp: "Transport Layer Security", hint: "General Security Concepts", example: "Cryptographic protocol securing network communications (successor to SSL).", exampleDe: null },
  { id: "g26", acr: "SSL", exp: "Secure Sockets Layer", hint: "General Security Concepts", example: "Predecessor to TLS, now deprecated.", exampleDe: null },
  { id: "g27", acr: "IPSec", exp: "Internet Protocol Security", hint: "General Security Concepts", example: "Suite of protocols securing IP communications (VPNs).", exampleDe: null },
  { id: "g28", acr: "ESP", exp: "Encapsulating Security Payload", hint: "General Security Concepts", example: "IPSec protocol providing encryption, integrity, and authentication.", exampleDe: null },
  { id: "g29", acr: "AH", exp: "Authentication Header", hint: "General Security Concepts", example: "IPSec protocol providing integrity/authentication without encryption.", exampleDe: null },
  { id: "g30", acr: "SAN", exp: "Subject Alternative Name (certificate)", hint: "General Security Concepts", example: "Certificate extension allowing multiple domains/hosts on one cert.", exampleDe: null },
  { id: "g31", acr: "CN", exp: "Common Name", hint: "General Security Concepts", example: "Field in a certificate identifying the entity (e.g., domain name).", exampleDe: null },
  { id: "g32", acr: "DAC", exp: "Discretionary Access Control", hint: "General Security Concepts", example: "Access model where the resource owner sets permissions.", exampleDe: null },
  { id: "g33", acr: "MAC", exp: "Mandatory Access Control", hint: "General Security Concepts", example: "Access model where a central authority enforces access based on labels.", exampleDe: null },
  { id: "g34", acr: "RBAC", exp: "Role-Based Access Control", hint: "General Security Concepts", example: "Access granted based on a user's assigned role.", exampleDe: null },
  { id: "g35", acr: "ABAC", exp: "Attribute-Based Access Control", hint: "General Security Concepts", example: "Access decisions based on user/resource/environment attributes.", exampleDe: null },
  { id: "g36", acr: "PAM", exp: "Privileged Access Management", hint: "General Security Concepts", example: "Tools/processes controlling and monitoring privileged accounts.", exampleDe: null },
  { id: "g37", acr: "SSO", exp: "Single Sign-On", hint: "General Security Concepts", example: "Allows one login to access multiple systems/applications.", exampleDe: null },
  { id: "g38", acr: "MFA", exp: "Multi-Factor Authentication", hint: "General Security Concepts", example: "Requires two or more independent credentials to authenticate.", exampleDe: null },
  { id: "g39", acr: "2FA", exp: "Two-Factor Authentication", hint: "General Security Concepts", example: "Subset of MFA using exactly two factors.", exampleDe: null },
  { id: "g40", acr: "OTP", exp: "One-Time Password", hint: "General Security Concepts", example: "Password valid for only one login session or transaction.", exampleDe: null },
  { id: "g41", acr: "TOTP", exp: "Time-based One-Time Password", hint: "General Security Concepts", example: "OTP that changes based on the current time.", exampleDe: null },
  { id: "g42", acr: "HOTP", exp: "HMAC-based One-Time Password", hint: "General Security Concepts", example: "OTP based on a counter and HMAC, changes with each use.", exampleDe: null },
  { id: "g43", acr: "SAML", exp: "Security Assertion Markup Language", hint: "General Security Concepts", example: "XML-based standard for exchanging authentication/authorization data (SSO).", exampleDe: null },
  { id: "g44", acr: "OAuth", exp: "Open Authorization", hint: "General Security Concepts", example: "Protocol allowing apps to access resources on a user's behalf without sharing passwords.", exampleDe: null },
  { id: "g45", acr: "OIDC", exp: "OpenID Connect", hint: "General Security Concepts", example: "Identity layer built on top of OAuth 2.0 for authentication.", exampleDe: null },
  { id: "g46", acr: "LDAP", exp: "Lightweight Directory Access Protocol", hint: "General Security Concepts", example: "Protocol for accessing and maintaining directory services (e.g., user accounts).", exampleDe: null },
  { id: "g47", acr: "LDAPS", exp: "LDAP Secure", hint: "General Security Concepts", example: "LDAP encrypted with SSL/TLS.", exampleDe: null },
  { id: "g48", acr: "RADIUS", exp: "Remote Authentication Dial-In User Service", hint: "General Security Concepts", example: "AAA protocol commonly used for network access authentication.", exampleDe: null },
  { id: "g49", acr: "TACACS+", exp: "Terminal Access Controller Access-Control System Plus", hint: "General Security Concepts", example: "Cisco AAA protocol separating authentication, authorization, and accounting.", exampleDe: null },
  { id: "g50", acr: "IAM", exp: "Identity and Access Management", hint: "General Security Concepts", example: "Framework of policies/technologies for managing digital identities.", exampleDe: null },
  { id: "g51", acr: "PoLP", exp: "Principle of Least Privilege", hint: "General Security Concepts", example: "Users/systems get only the minimum access needed to function.", exampleDe: null },

  // 2. Threats, Vulnerabilities & Mitigations
  { id: "th1", acr: "APT", exp: "Advanced Persistent Threat", hint: "Threats, Vulnerabilities & Mitigations", example: "Sophisticated, prolonged, targeted attack usually by well-resourced actors.", exampleDe: null },
  { id: "th2", acr: "IOC", exp: "Indicator of Compromise", hint: "Threats, Vulnerabilities & Mitigations", example: "Forensic artifact suggesting a system has been breached (e.g., hash, IP).", exampleDe: null },
  { id: "th3", acr: "TTP", exp: "Tactics, Techniques, and Procedures", hint: "Threats, Vulnerabilities & Mitigations", example: "Behavioral patterns used to describe how attackers operate.", exampleDe: null },
  { id: "th4", acr: "RAT", exp: "Remote Access Trojan", hint: "Threats, Vulnerabilities & Mitigations", example: "Malware giving an attacker remote control of a victim's machine.", exampleDe: null },
  { id: "th5", acr: "C2 / C&C", exp: "Command and Control", hint: "Threats, Vulnerabilities & Mitigations", example: "Infrastructure attackers use to communicate with compromised systems.", exampleDe: null },
  { id: "th6", acr: "DDoS", exp: "Distributed Denial of Service", hint: "Threats, Vulnerabilities & Mitigations", example: "DoS attack launched from multiple sources simultaneously.", exampleDe: null },
  { id: "th7", acr: "DoS", exp: "Denial of Service", hint: "Threats, Vulnerabilities & Mitigations", example: "Attack aimed at making a service unavailable.", exampleDe: null },
  { id: "th8", acr: "MITM", exp: "Man-in-the-Middle", hint: "Threats, Vulnerabilities & Mitigations", example: "Attack where the adversary intercepts communication between two parties.", exampleDe: null },
  { id: "th9", acr: "XSS", exp: "Cross-Site Scripting", hint: "Threats, Vulnerabilities & Mitigations", example: "Injection attack where malicious scripts run in a victim's browser.", exampleDe: null },
  { id: "th10", acr: "CSRF", exp: "Cross-Site Request Forgery", hint: "Threats, Vulnerabilities & Mitigations", example: "Tricks a user's browser into performing unwanted actions on a trusted site.", exampleDe: null },
  { id: "th11", acr: "SQLi", exp: "SQL Injection", hint: "Threats, Vulnerabilities & Mitigations", example: "Injecting malicious SQL to manipulate a database via user input.", exampleDe: null },
  { id: "th12", acr: "RCE", exp: "Remote Code Execution", hint: "Threats, Vulnerabilities & Mitigations", example: "Vulnerability allowing an attacker to run arbitrary code remotely.", exampleDe: null },
  { id: "th13", acr: "LFI", exp: "Local File Inclusion", hint: "Threats, Vulnerabilities & Mitigations", example: "Vulnerability allowing inclusion of local files via unsanitized input.", exampleDe: null },
  { id: "th14", acr: "RFI", exp: "Remote File Inclusion", hint: "Threats, Vulnerabilities & Mitigations", example: "Vulnerability allowing inclusion of remote files via unsanitized input.", exampleDe: null },
  { id: "th15", acr: "SSRF", exp: "Server-Side Request Forgery", hint: "Threats, Vulnerabilities & Mitigations", example: "Tricks a server into making unintended requests, often to internal resources.", exampleDe: null },
  { id: "th16", acr: "XXE", exp: "XML External Entity", hint: "Threats, Vulnerabilities & Mitigations", example: "Attack exploiting XML parsers to access files or internal systems.", exampleDe: null },
  { id: "th17", acr: "BEC", exp: "Business Email Compromise", hint: "Threats, Vulnerabilities & Mitigations", example: "Social engineering attack targeting business email accounts for fraud.", exampleDe: null },
  { id: "th18", acr: "CVE", exp: "Common Vulnerabilities and Exposures", hint: "Threats, Vulnerabilities & Mitigations", example: "Publicly indexed catalog of known vulnerabilities.", exampleDe: null },
  { id: "th19", acr: "CVSS", exp: "Common Vulnerability Scoring System", hint: "Threats, Vulnerabilities & Mitigations", example: "Standardized scoring for the severity of vulnerabilities.", exampleDe: null },
  { id: "th20", acr: "CWE", exp: "Common Weakness Enumeration", hint: "Threats, Vulnerabilities & Mitigations", example: "Categorized list of common software/hardware weakness types.", exampleDe: null },
  { id: "th21", acr: "CPE", exp: "Common Platform Enumeration", hint: "Threats, Vulnerabilities & Mitigations", example: "Standardized naming scheme for identifying software/hardware platforms.", exampleDe: null },
  { id: "th22", acr: "OWASP", exp: "Open Web Application Security Project", hint: "Threats, Vulnerabilities & Mitigations", example: "Nonprofit providing resources on web app security (famous for Top 10).", exampleDe: null },
  { id: "th23", acr: "ARP", exp: "Address Resolution Protocol", hint: "Threats, Vulnerabilities & Mitigations", example: "Maps IP addresses to MAC addresses; commonly spoofed in MITM attacks.", exampleDe: null },
  { id: "th24", acr: "DNS", exp: "Domain Name System", hint: "Threats, Vulnerabilities & Mitigations", example: "Resolves domain names to IP addresses; frequent attack target.", exampleDe: null },
  { id: "th25", acr: "VLAN", exp: "Virtual Local Area Network", hint: "Threats, Vulnerabilities & Mitigations", example: "Logical network segmentation within physical infrastructure.", exampleDe: null },
  { id: "th26", acr: "ACL", exp: "Access Control List", hint: "Threats, Vulnerabilities & Mitigations", example: "Rules defining allowed/denied traffic or permissions.", exampleDe: null },
  { id: "th27", acr: "EDR", exp: "Endpoint Detection and Response", hint: "Threats, Vulnerabilities & Mitigations", example: "Tool monitoring endpoints for threats and enabling response actions.", exampleDe: null },
  { id: "th28", acr: "XDR", exp: "Extended Detection and Response", hint: "Threats, Vulnerabilities & Mitigations", example: "Extends EDR by correlating data across endpoints, network, cloud, etc.", exampleDe: null },
  { id: "th29", acr: "MDR", exp: "Managed Detection and Response", hint: "Threats, Vulnerabilities & Mitigations", example: "Outsourced security service providing threat detection/response.", exampleDe: null },
  { id: "th30", acr: "AV", exp: "Antivirus", hint: "Threats, Vulnerabilities & Mitigations", example: "Software detecting/removing known malware signatures.", exampleDe: null },
  { id: "th31", acr: "HIPS", exp: "Host-based Intrusion Prevention System", hint: "Threats, Vulnerabilities & Mitigations", example: "Software on a host that detects and blocks malicious activity.", exampleDe: null },
  { id: "th32", acr: "NIPS", exp: "Network-based Intrusion Prevention System", hint: "Threats, Vulnerabilities & Mitigations", example: "Network device that detects and blocks malicious traffic.", exampleDe: null },
  { id: "th33", acr: "IDS", exp: "Intrusion Detection System", hint: "Threats, Vulnerabilities & Mitigations", example: "Monitors traffic/systems for malicious activity, alerts only.", exampleDe: null },
  { id: "th34", acr: "IPS", exp: "Intrusion Prevention System", hint: "Threats, Vulnerabilities & Mitigations", example: "Monitors and actively blocks malicious traffic.", exampleDe: null },
  { id: "th35", acr: "WAF", exp: "Web Application Firewall", hint: "Threats, Vulnerabilities & Mitigations", example: "Filters/monitors HTTP traffic to protect web applications.", exampleDe: null },
  { id: "th36", acr: "NGFW", exp: "Next-Generation Firewall", hint: "Threats, Vulnerabilities & Mitigations", example: "Firewall with deep packet inspection, app awareness, and IPS features.", exampleDe: null },
  { id: "th37", acr: "UTM", exp: "Unified Threat Management", hint: "Threats, Vulnerabilities & Mitigations", example: "All-in-one security appliance combining firewall, AV, IPS, etc.", exampleDe: null },
  { id: "th38", acr: "DLP", exp: "Data Loss Prevention", hint: "Threats, Vulnerabilities & Mitigations", example: "Tools/policies preventing sensitive data from leaving an organization.", exampleDe: null },
  { id: "th39", acr: "SOAR", exp: "Security Orchestration, Automation, and Response", hint: "Threats, Vulnerabilities & Mitigations", example: "Platform automating incident response workflows.", exampleDe: null },
  { id: "th40", acr: "SIEM", exp: "Security Information and Event Management", hint: "Threats, Vulnerabilities & Mitigations", example: "Aggregates and correlates logs for detection/analysis.", exampleDe: null },
  { id: "th41", acr: "UEBA", exp: "User and Entity Behavior Analytics", hint: "Threats, Vulnerabilities & Mitigations", example: "Detects anomalies by analyzing behavior patterns of users/systems.", exampleDe: null },
  { id: "th42", acr: "HoneyPot", exp: "Decoy system to attract & study attackers", hint: "Threats, Vulnerabilities & Mitigations", example: "Not an acronym, but a common term worth knowing for the exam.", exampleDe: null },
  { id: "th43", acr: "PoC", exp: "Proof of Concept", hint: "Threats, Vulnerabilities & Mitigations", example: "Demonstration exploit showing a vulnerability is exploitable.", exampleDe: null },
  { id: "th44", acr: "Zero-Day", exp: "Vulnerability unknown to vendor, no patch yet", hint: "Threats, Vulnerabilities & Mitigations", example: "Not a classic acronym, but core exam vocabulary.", exampleDe: null },

  // 3. Security Architecture
  { id: "ar1", acr: "DMZ", exp: "Demilitarized Zone", hint: "Security Architecture", example: "Network segment isolating public-facing services from the internal LAN.", exampleDe: null },
  { id: "ar2", acr: "NAT", exp: "Network Address Translation", hint: "Security Architecture", example: "Translates private IPs to public IPs (and vice versa).", exampleDe: null },
  { id: "ar3", acr: "SDN", exp: "Software-Defined Networking", hint: "Security Architecture", example: "Separates network control logic from physical routing hardware.", exampleDe: null },
  { id: "ar4", acr: "SD-WAN", exp: "Software-Defined Wide Area Network", hint: "Security Architecture", example: "Virtualized WAN management for optimizing multi-site connectivity.", exampleDe: null },
  { id: "ar5", acr: "SASE", exp: "Secure Access Service Edge", hint: "Security Architecture", example: "Converges networking and security into a cloud-delivered service.", exampleDe: null },
  { id: "ar6", acr: "ZTA", exp: "Zero Trust Architecture", hint: "Security Architecture", example: "Security model that trusts nothing by default, verifies every request.", exampleDe: null },
  { id: "ar7", acr: "ZTNA", exp: "Zero Trust Network Access", hint: "Security Architecture", example: "Access model enforcing zero trust principles for network resources.", exampleDe: null },
  { id: "ar8", acr: "VPN", exp: "Virtual Private Network", hint: "Security Architecture", example: "Encrypted tunnel for secure remote connectivity.", exampleDe: null },
  { id: "ar9", acr: "IaaS", exp: "Infrastructure as a Service", hint: "Security Architecture", example: "Cloud model providing virtualized computing infrastructure.", exampleDe: null },
  { id: "ar10", acr: "PaaS", exp: "Platform as a Service", hint: "Security Architecture", example: "Cloud model providing a platform for developing/deploying apps.", exampleDe: null },
  { id: "ar11", acr: "SaaS", exp: "Software as a Service", hint: "Security Architecture", example: "Cloud model delivering fully managed software applications.", exampleDe: null },
  { id: "ar12", acr: "CASB", exp: "Cloud Access Security Broker", hint: "Security Architecture", example: "Enforces security policies between users and cloud services.", exampleDe: null },
  { id: "ar13", acr: "CSP", exp: "Cloud Service Provider", hint: "Security Architecture", example: "Company offering cloud computing services (AWS, Azure, GCP).", exampleDe: null },
  { id: "ar14", acr: "CDN", exp: "Content Delivery Network", hint: "Security Architecture", example: "Distributed servers delivering content with lower latency, some DDoS protection.", exampleDe: null },
  { id: "ar15", acr: "IaC", exp: "Infrastructure as Code", hint: "Security Architecture", example: "Managing infrastructure through machine-readable definition files.", exampleDe: null },
  { id: "ar16", acr: "API", exp: "Application Programming Interface", hint: "Security Architecture", example: "Interface allowing software components to communicate.", exampleDe: null },
  { id: "ar17", acr: "SDLC", exp: "Software Development Life Cycle", hint: "Security Architecture", example: "Structured process for developing software, including security steps.", exampleDe: null },
  { id: "ar18", acr: "DevSecOps", exp: "Development, Security, and Operations", hint: "Security Architecture", example: "Integrates security practices throughout the DevOps pipeline.", exampleDe: null },
  { id: "ar19", acr: "CI/CD", exp: "Continuous Integration/Continuous Deployment", hint: "Security Architecture", example: "Automated pipeline for building, testing, and deploying code.", exampleDe: null },
  { id: "ar20", acr: "HA", exp: "High Availability", hint: "Security Architecture", example: "Design ensuring systems remain operational with minimal downtime.", exampleDe: null },
  { id: "ar21", acr: "FT", exp: "Fault Tolerance", hint: "Security Architecture", example: "System's ability to continue operating despite component failure.", exampleDe: null },
  { id: "ar22", acr: "RAID", exp: "Redundant Array of Independent Disks", hint: "Security Architecture", example: "Combines multiple disks for redundancy and/or performance.", exampleDe: null },
  { id: "ar23", acr: "SAN", exp: "Storage Area Network", hint: "Security Architecture", example: "Dedicated network providing block-level storage access.", exampleDe: null },
  { id: "ar24", acr: "NAS", exp: "Network Attached Storage", hint: "Security Architecture", example: "Storage device connected to a network providing file-level access.", exampleDe: null },
  { id: "ar25", acr: "IoT", exp: "Internet of Things", hint: "Security Architecture", example: "Network of connected physical devices with embedded sensors/software.", exampleDe: null },
  { id: "ar26", acr: "ICS", exp: "Industrial Control System", hint: "Security Architecture", example: "Systems controlling industrial processes (manufacturing, utilities).", exampleDe: null },
  { id: "ar27", acr: "SCADA", exp: "Supervisory Control and Data Acquisition", hint: "Security Architecture", example: "ICS subtype used for large-scale, geographically distributed control.", exampleDe: null },
  { id: "ar28", acr: "PLC", exp: "Programmable Logic Controller", hint: "Security Architecture", example: "Industrial computer controlling machinery/processes.", exampleDe: null },
  { id: "ar29", acr: "OT", exp: "Operational Technology", hint: "Security Architecture", example: "Hardware/software controlling physical devices and processes.", exampleDe: null },
  { id: "ar30", acr: "IT", exp: "Information Technology", hint: "Security Architecture", example: "Systems managing data and computing (contrasted with OT).", exampleDe: null },
  { id: "ar31", acr: "RTOS", exp: "Real-Time Operating System", hint: "Security Architecture", example: "OS designed for time-critical processing (common in embedded/IoT).", exampleDe: null },
  { id: "ar32", acr: "SoC", exp: "System on Chip", hint: "Security Architecture", example: "Integrated circuit combining most components of a computer.", exampleDe: null },
  { id: "ar33", acr: "VDI", exp: "Virtual Desktop Infrastructure", hint: "Security Architecture", example: "Hosts desktop environments on a central server, accessed remotely.", exampleDe: null },
  { id: "ar34", acr: "VM", exp: "Virtual Machine", hint: "Security Architecture", example: "Software emulation of a physical computer.", exampleDe: null },
  { id: "ar35", acr: "VMM / Hypervisor", exp: "Virtual Machine Monitor", hint: "Security Architecture", example: "Software that creates/manages virtual machines.", exampleDe: null },
  { id: "ar36", acr: "MDM", exp: "Mobile Device Management", hint: "Security Architecture", example: "Tools for managing/securing mobile devices in an organization.", exampleDe: null },
  { id: "ar37", acr: "UEM", exp: "Unified Endpoint Management", hint: "Security Architecture", example: "Manages all endpoint types (mobile, desktop, IoT) from one platform.", exampleDe: null },
  { id: "ar38", acr: "BYOD", exp: "Bring Your Own Device", hint: "Security Architecture", example: "Policy allowing employees to use personal devices for work.", exampleDe: null },
  { id: "ar39", acr: "COPE", exp: "Corporate-Owned, Personally Enabled", hint: "Security Architecture", example: "Company-owned devices that employees can also use personally.", exampleDe: null },
  { id: "ar40", acr: "CYOD", exp: "Choose Your Own Device", hint: "Security Architecture", example: "Employees pick from a company-approved list of devices.", exampleDe: null },

  // 4. Security Operations
  { id: "op1", acr: "SOC", exp: "Security Operations Center", hint: "Security Operations", example: "Team/facility responsible for monitoring and responding to security events.", exampleDe: null },
  { id: "op2", acr: "CSIRT", exp: "Computer Security Incident Response Team", hint: "Security Operations", example: "Team dedicated to handling security incidents.", exampleDe: null },
  { id: "op3", acr: "IR", exp: "Incident Response", hint: "Security Operations", example: "Structured process for detecting, containing, and recovering from incidents.", exampleDe: null },
  { id: "op4", acr: "IRP", exp: "Incident Response Plan", hint: "Security Operations", example: "Documented procedures for handling security incidents.", exampleDe: null },
  { id: "op5", acr: "BCP", exp: "Business Continuity Plan", hint: "Security Operations", example: "Plan ensuring critical business functions continue during a disruption.", exampleDe: null },
  { id: "op6", acr: "DRP", exp: "Disaster Recovery Plan", hint: "Security Operations", example: "Plan for restoring IT systems after a disaster.", exampleDe: null },
  { id: "op7", acr: "BIA", exp: "Business Impact Analysis", hint: "Security Operations", example: "Identifies critical functions and the impact of their disruption.", exampleDe: null },
  { id: "op8", acr: "RTO", exp: "Recovery Time Objective", hint: "Security Operations", example: "Maximum acceptable time to restore a system after an outage.", exampleDe: null },
  { id: "op9", acr: "RPO", exp: "Recovery Point Objective", hint: "Security Operations", example: "Maximum acceptable amount of data loss, measured in time.", exampleDe: null },
  { id: "op10", acr: "MTTR", exp: "Mean Time to Repair (or Recover)", hint: "Security Operations", example: "Average time to fix/restore a failed system.", exampleDe: null },
  { id: "op11", acr: "MTTF", exp: "Mean Time to Failure", hint: "Security Operations", example: "Average time a non-repairable system operates before failing.", exampleDe: null },
  { id: "op12", acr: "MTBF", exp: "Mean Time Between Failures", hint: "Security Operations", example: "Average time between failures of a repairable system.", exampleDe: null },
  { id: "op13", acr: "COOP", exp: "Continuity of Operations Plan", hint: "Security Operations", example: "Plan ensuring essential government/business functions continue.", exampleDe: null },
  { id: "op14", acr: "DFIR", exp: "Digital Forensics and Incident Response", hint: "Security Operations", example: "Discipline combining forensic investigation with incident handling.", exampleDe: null },
  { id: "op15", acr: "CoC", exp: "Chain of Custody", hint: "Security Operations", example: "Documented, unbroken trail of evidence handling for legal admissibility.", exampleDe: null },
  { id: "op16", acr: "SOP", exp: "Standard Operating Procedure", hint: "Security Operations", example: "Documented step-by-step process for routine operations.", exampleDe: null },
  { id: "op17", acr: "NDA", exp: "Non-Disclosure Agreement", hint: "Security Operations", example: "Legal contract protecting confidential information.", exampleDe: null },
  { id: "op18", acr: "SLA", exp: "Service Level Agreement", hint: "Security Operations", example: "Contract defining expected service performance/response standards.", exampleDe: null },
  { id: "op19", acr: "MOU", exp: "Memorandum of Understanding", hint: "Security Operations", example: "Informal agreement outlining mutual intentions between parties.", exampleDe: null },
  { id: "op20", acr: "MSA", exp: "Master Service Agreement", hint: "Security Operations", example: "Contract establishing terms governing future work agreements.", exampleDe: null },
  { id: "op21", acr: "SOW", exp: "Statement of Work", hint: "Security Operations", example: "Document defining project-specific tasks, deliverables, and timelines.", exampleDe: null },
  { id: "op22", acr: "PII", exp: "Personally Identifiable Information", hint: "Security Operations", example: "Data that can identify a specific individual.", exampleDe: null },
  { id: "op23", acr: "PHI", exp: "Protected Health Information", hint: "Security Operations", example: "Health-related data protected under regulations like HIPAA.", exampleDe: null },
  { id: "op24", acr: "GDPR", exp: "General Data Protection Regulation", hint: "Security Operations", example: "EU regulation governing data privacy and protection.", exampleDe: null },
  { id: "op25", acr: "HIPAA", exp: "Health Insurance Portability and Accountability Act", hint: "Security Operations", example: "US law protecting medical information privacy.", exampleDe: null },
  { id: "op26", acr: "PCI DSS", exp: "Payment Card Industry Data Security Standard", hint: "Security Operations", example: "Security standard for organizations handling card payments.", exampleDe: null },
  { id: "op27", acr: "NIST", exp: "National Institute of Standards and Technology", hint: "Security Operations", example: "US agency publishing widely used cybersecurity frameworks/standards.", exampleDe: null },
  { id: "op28", acr: "ISO", exp: "International Organization for Standardization", hint: "Security Operations", example: "Publishes international standards, including ISO 27001 (security).", exampleDe: null },
  { id: "op29", acr: "COBIT", exp: "Control Objectives for Information and Related Technologies", hint: "Security Operations", example: "Framework for IT governance and management.", exampleDe: null },
  { id: "op30", acr: "STIX", exp: "Structured Threat Information Expression", hint: "Security Operations", example: "Standardized language for describing cyber threat intelligence.", exampleDe: null },
  { id: "op31", acr: "TAXII", exp: "Trusted Automated Exchange of Intelligence Information", hint: "Security Operations", example: "Protocol for sharing threat intelligence (often paired with STIX).", exampleDe: null },
  { id: "op32", acr: "OSINT", exp: "Open-Source Intelligence", hint: "Security Operations", example: "Intelligence gathered from publicly available sources.", exampleDe: null },
  { id: "op33", acr: "SANS", exp: "SysAdmin, Audit, Network, Security (org)", hint: "Security Operations", example: "Organization providing cybersecurity training and research.", exampleDe: null },
  { id: "op34", acr: "CERT", exp: "Computer Emergency Response Team", hint: "Security Operations", example: "Team responsible for responding to cybersecurity incidents (like CSIRT).", exampleDe: null },
  { id: "op35", acr: "WORM", exp: "Write Once, Read Many", hint: "Security Operations", example: "Storage that can't be modified after writing — useful for log integrity.", exampleDe: null },
  { id: "op36", acr: "UAT", exp: "User Acceptance Testing", hint: "Security Operations", example: "Testing phase where end users validate a system before release.", exampleDe: null },
  { id: "op37", acr: "PT", exp: "Penetration Testing", hint: "Security Operations", example: "Authorized simulated attack to find exploitable vulnerabilities.", exampleDe: null },
  { id: "op38", acr: "RTM", exp: "Red Team / Blue Team", hint: "Security Operations", example: "Red = attackers, Blue = defenders in simulated exercises.", exampleDe: null },
  { id: "op39", acr: "BAS", exp: "Breach and Attack Simulation", hint: "Security Operations", example: "Automated tool continuously testing defenses against simulated attacks.", exampleDe: null },

  // 5. Governance, Risk & Compliance
  { id: "gr1", acr: "GRC", exp: "Governance, Risk, and Compliance", hint: "Governance, Risk & Compliance", example: "Integrated approach to managing governance, risk, and regulatory compliance.", exampleDe: null },
  { id: "gr2", acr: "RA", exp: "Risk Assessment (GRC)", hint: "Governance, Risk & Compliance", example: "Process of identifying and evaluating risks.", exampleDe: null },
  { id: "gr3", acr: "RMF", exp: "Risk Management Framework", hint: "Governance, Risk & Compliance", example: "NIST framework for managing organizational cybersecurity risk.", exampleDe: null },
  { id: "gr4", acr: "ALE", exp: "Annualized Loss Expectancy", hint: "Governance, Risk & Compliance", example: "Expected yearly financial loss from a risk (SLE × ARO).", exampleDe: null },
  { id: "gr5", acr: "SLE", exp: "Single Loss Expectancy", hint: "Governance, Risk & Compliance", example: "Expected monetary loss from a single occurrence of a risk.", exampleDe: null },
  { id: "gr6", acr: "ARO", exp: "Annualized Rate of Occurrence", hint: "Governance, Risk & Compliance", example: "Estimated frequency of a risk event occurring per year.", exampleDe: null },
  { id: "gr7", acr: "KRI", exp: "Key Risk Indicator", hint: "Governance, Risk & Compliance", example: "Metric signaling increasing risk exposure.", exampleDe: null },
  { id: "gr8", acr: "KPI", exp: "Key Performance Indicator", hint: "Governance, Risk & Compliance", example: "Metric measuring performance against objectives.", exampleDe: null },
  { id: "gr9", acr: "SPoF", exp: "Single Point of Failure", hint: "Governance, Risk & Compliance", example: "Component whose failure would cause the entire system to fail.", exampleDe: null },
  { id: "gr10", acr: "TCO", exp: "Total Cost of Ownership", hint: "Governance, Risk & Compliance", example: "Full cost of a system including purchase, operation, and maintenance.", exampleDe: null },
  { id: "gr11", acr: "ROI", exp: "Return on Investment", hint: "Governance, Risk & Compliance", example: "Measure of profitability relative to cost.", exampleDe: null },
  { id: "gr12", acr: "DPO", exp: "Data Protection Officer", hint: "Governance, Risk & Compliance", example: "Role responsible for overseeing data protection strategy/compliance.", exampleDe: null },
  { id: "gr13", acr: "DPA", exp: "Data Processing Agreement", hint: "Governance, Risk & Compliance", example: "Contract governing how a third party processes personal data.", exampleDe: null },
  { id: "gr14", acr: "EULA", exp: "End User License Agreement", hint: "Governance, Risk & Compliance", example: "Legal agreement between software provider and user.", exampleDe: null },
  { id: "gr15", acr: "AUP", exp: "Acceptable Use Policy", hint: "Governance, Risk & Compliance", example: "Policy defining acceptable use of company systems/resources.", exampleDe: null },
];
