// Spanisch-Wortpaare (Standard-/Lehrbuch-Spanisch)
export const PAIRS = [
  { id: "v1", es: "ser", de: "sein (dauerhaft/Identität)", hint: "unregelmäßig", ipaEs: "/ser/", ipaDe: "/zaɪn/", example: "Ella es profesora.", exampleDe: "Sie ist Lehrerin." },
  { id: "v2", es: "estar", de: "sein (Zustand/Ort)", hint: "unregelmäßig", ipaEs: "/esˈtar/", ipaDe: "/zaɪn/", example: "Estoy en casa.", exampleDe: "Ich bin zu Hause." },
  { id: "v3", es: "tener", de: "haben", hint: "unregelmäßig", ipaEs: "/teˈner/", ipaDe: "/ˈhaːbən/", example: "Tengo dos hermanos.", exampleDe: "Ich habe zwei Geschwister." },
  { id: "v4", es: "hacer", de: "machen, tun", hint: "unregelmäßig", ipaEs: "/aˈser/", ipaDe: "/ˈmaxən/", example: "¿Qué haces hoy?", exampleDe: "Was machst du heute?" },
  { id: "v5", es: "ir", de: "gehen", hint: "unregelmäßig", ipaEs: "/ir/", ipaDe: "/ˈgeːən/", example: "Voy al trabajo.", exampleDe: "Ich gehe zur Arbeit." },
  { id: "v6", es: "poder", de: "können", hint: "unregelmäßig", ipaEs: "/poˈðer/", ipaDe: "/ˈkœnən/", example: "¿Puedes ayudarme?", exampleDe: "Kannst du mir helfen?" },
  { id: "v7", es: "decir", de: "sagen", hint: "unregelmäßig", ipaEs: "/deˈsir/", ipaDe: "/ˈzaːgən/", example: "¿Qué dices?", exampleDe: "Was sagst du?" },
  { id: "v8", es: "ver", de: "sehen", hint: "unregelmäßig", ipaEs: "/ber/", ipaDe: "/ˈzeːən/", example: "Veo la ciudad desde aquí.", exampleDe: "Ich sehe die Stadt von hier aus." },
  { id: "v9", es: "dar", de: "geben", hint: "unregelmäßig", ipaEs: "/dar/", ipaDe: "/ˈgeːbən/", example: "Te doy mi número.", exampleDe: "Ich gebe dir meine Nummer." },
  { id: "v10", es: "saber", de: "wissen", hint: "unregelmäßig", ipaEs: "/saˈβer/", ipaDe: "/ˈvɪsən/", example: "No sé la respuesta.", exampleDe: "Ich weiß die Antwort nicht." },
  { id: "v11", es: "querer", de: "wollen / lieben", hint: "unregelmäßig", ipaEs: "/keˈrer/", ipaDe: "/ˈvɔlən/", example: "Quiero aprender español.", exampleDe: "Ich will Spanisch lernen." },
  { id: "v12", es: "llegar", de: "ankommen", hint: "regelmäßig", ipaEs: "/ʝeˈɣar/", ipaDe: "/ˈankɔmən/", example: "Llego a las ocho.", exampleDe: "Ich komme um acht an." },
  { id: "v13", es: "pasar", de: "passieren, vorbeigehen", hint: "regelmäßig", ipaEs: "/paˈsar/", ipaDe: "/paˈsiːrən/", example: "¿Qué pasa?", exampleDe: "Was ist los?" },
  { id: "v14", es: "deber", de: "sollen, müssen", hint: "regelmäßig", ipaEs: "/deˈβer/", ipaDe: "/ˈzɔlən/", example: "Debo trabajar mañana.", exampleDe: "Ich muss morgen arbeiten." },
  { id: "v15", es: "hablar", de: "sprechen", hint: "regelmäßig", ipaEs: "/aˈβlar/", ipaDe: "/ˈʃprɛçən/", example: "Hablo un poco de español.", exampleDe: "Ich spreche ein bisschen Spanisch." },
  { id: "q1", es: "qué", de: "was", hint: "Fragewort", example: "¿Qué es esto?", exampleDe: "Was ist das?" },
  { id: "q2", es: "cómo", de: "wie", hint: "Fragewort", example: "¿Cómo estás?", exampleDe: "Wie geht es dir?" },
  { id: "q3", es: "cuándo", de: "wann", hint: "Fragewort", example: "¿Cuándo llegas?", exampleDe: "Wann kommst du an?" },
  { id: "q4", es: "dónde", de: "wo", hint: "Fragewort", example: "¿Dónde vives?", exampleDe: "Wo wohnst du?" },
  { id: "q5", es: "por qué", de: "warum", hint: "Fragewort", example: "¿Por qué no vienes?", exampleDe: "Warum kommst du nicht?" },
  { id: "q6", es: "quién", de: "wer", hint: "Fragewort", example: "¿Quién es él?", exampleDe: "Wer ist er?" },
  { id: "q7", es: "y", de: "und", hint: "Konnektor", example: "Tú y yo.", exampleDe: "Du und ich." },
  { id: "q8", es: "pero", de: "aber", hint: "Konnektor", example: "Quiero ir, pero no puedo.", exampleDe: "Ich will gehen, aber ich kann nicht." },
  { id: "n1", es: "el tiempo", de: "die Zeit / das Wetter", hint: "männlich", example: "No tengo tiempo.", exampleDe: "Ich habe keine Zeit." },
  { id: "n2", es: "el día", de: "der Tag", hint: "männlich", example: "Hoy es un buen día.", exampleDe: "Heute ist ein guter Tag." },
  { id: "n3", es: "el agua", de: "das Wasser", hint: "weiblich (Ausnahme: el agua)", example: "Necesito agua.", exampleDe: "Ich brauche Wasser." },
  { id: "n4", es: "la comida", de: "das Essen", hint: "weiblich", example: "La comida está lista.", exampleDe: "Das Essen ist fertig." },
  { id: "n5", es: "el trabajo", de: "die Arbeit", hint: "männlich", example: "Tengo mucho trabajo.", exampleDe: "Ich habe viel Arbeit." },
  { id: "n6", es: "el dinero", de: "das Geld", hint: "männlich", example: "No tengo dinero.", exampleDe: "Ich habe kein Geld." },
  { id: "n7", es: "la calle", de: "die Straße", hint: "weiblich", example: "Vivo en esta calle.", exampleDe: "Ich wohne in dieser Straße." },
  { id: "n8", es: "la ciudad", de: "die Stadt", hint: "weiblich", example: "Bogotá es una ciudad grande.", exampleDe: "Bogotá ist eine große Stadt." },
  { id: "n9", es: "la familia", de: "die Familie", hint: "weiblich", example: "Mi familia es grande.", exampleDe: "Meine Familie ist groß." },
  { id: "n10", es: "el amigo", de: "der Freund", hint: "männlich", example: "Es mi mejor amigo.", exampleDe: "Er ist mein bester Freund." },
  { id: "n11", es: "el amor", de: "die Liebe", hint: "männlich", example: "El amor es importante.", exampleDe: "Die Liebe ist wichtig." },
  { id: "n12", es: "la vida", de: "das Leben", hint: "weiblich", example: "Me gusta mi vida.", exampleDe: "Ich mag mein Leben." },
  { id: "n13", es: "el mundo", de: "die Welt", hint: "männlich", example: "El mundo es grande.", exampleDe: "Die Welt ist groß." },
  { id: "n14", es: "el momento", de: "der Moment", hint: "männlich", example: "Un momento, por favor.", exampleDe: "Einen Moment, bitte." },
  { id: "n15", es: "la casa", de: "das Haus", hint: "weiblich", example: "Mi casa es pequeña.", exampleDe: "Mein Haus ist klein." },
  { id: "a1", es: "bueno", de: "gut", hint: "Adjektiv", example: "Es un buen libro.", exampleDe: "Es ist ein gutes Buch." },
  { id: "a2", es: "malo", de: "schlecht", hint: "Adjektiv", example: "El tiempo está malo.", exampleDe: "Das Wetter ist schlecht." },
  { id: "a3", es: "grande", de: "groß", hint: "Adjektiv", example: "Es una casa grande.", exampleDe: "Es ist ein großes Haus." },
  { id: "a4", es: "pequeño", de: "klein", hint: "Adjektiv", example: "Es un problema pequeño.", exampleDe: "Es ist ein kleines Problem." },
  { id: "a5", es: "nuevo", de: "neu", hint: "Adjektiv", example: "Tengo un teléfono nuevo.", exampleDe: "Ich habe ein neues Telefon." },
  { id: "a6", es: "mucho", de: "viel", hint: "Adjektiv", example: "Hay mucha gente aquí.", exampleDe: "Hier sind viele Leute." },
  { id: "a7", es: "poco", de: "wenig", hint: "Adjektiv", example: "Hablo poco español.", exampleDe: "Ich spreche wenig Spanisch." },
  { id: "a8", es: "mismo", de: "gleich, selbst", hint: "Adjektiv", example: "Es el mismo problema.", exampleDe: "Es ist das gleiche Problem." },
  { id: "a9", es: "otro", de: "anderer", hint: "Adjektiv", example: "Quiero otro café.", exampleDe: "Ich möchte einen anderen Kaffee." },
  { id: "a10", es: "todo", de: "alles, ganz", hint: "Adjektiv", example: "Todo está bien.", exampleDe: "Alles ist gut." },
  { id: "f1", es: "la madre", de: "die Mutter", hint: "weiblich", example: "Mi madre vive en Alemania.", exampleDe: "Meine Mutter lebt in Deutschland." },
  { id: "f2", es: "el padre", de: "der Vater", hint: "männlich", example: "Mi padre trabaja mucho.", exampleDe: "Mein Vater arbeitet viel." },
  { id: "f3", es: "el hermano", de: "der Bruder", hint: "männlich", example: "Tengo un hermano.", exampleDe: "Ich habe einen Bruder." },
  { id: "f4", es: "la hermana", de: "die Schwester", hint: "weiblich", example: "Mi hermana es mayor.", exampleDe: "Meine Schwester ist älter." },
  { id: "f5", es: "el hijo", de: "der Sohn", hint: "männlich", example: "Es mi hijo.", exampleDe: "Er ist mein Sohn." },
  { id: "f6", es: "la hija", de: "die Tochter", hint: "weiblich", example: "Es mi hija.", exampleDe: "Sie ist meine Tochter." },
  { id: "f7", es: "la pareja", de: "der/die Partner/in", hint: "weiblich, geschlechtsneutral verwendet", example: "Ella es mi pareja.", exampleDe: "Sie ist meine Partnerin." },
  { id: "f8", es: "el abuelo", de: "der Großvater", hint: "männlich", example: "Mi abuelo tiene ochenta años.", exampleDe: "Mein Großvater ist achtzig Jahre alt." },
  { id: "f9", es: "la abuela", de: "die Großmutter", hint: "weiblich", example: "Mi abuela cocina muy bien.", exampleDe: "Meine Großmutter kocht sehr gut." },
  { id: "e1", es: "por favor", de: "bitte", hint: "Redewendung", example: "Un café, por favor.", exampleDe: "Einen Kaffee, bitte." },
  { id: "e2", es: "gracias", de: "danke", hint: "Redewendung", example: "Muchas gracias.", exampleDe: "Vielen Dank." },
  { id: "e3", es: "de nada", de: "gern geschehen", hint: "Redewendung", example: "— Gracias. — De nada.", exampleDe: "— Danke. — Gern geschehen." },
  { id: "e4", es: "buenos días", de: "guten Morgen/Tag", hint: "Redewendung", example: "¡Buenos días a todos!", exampleDe: "Guten Morgen an alle!" },
  { id: "e5", es: "buenas noches", de: "gute Nacht", hint: "Redewendung", example: "Buenas noches, que descanses.", exampleDe: "Gute Nacht, schlaf gut." },
  { id: "pn1", es: "yo", de: "ich", hint: "Personalpronomen", example: "Yo hablo español.", exampleDe: "Ich spreche Spanisch." },
  { id: "pn2", es: "tú", de: "du", hint: "Personalpronomen", example: "Tú eres mi amigo.", exampleDe: "Du bist mein Freund." },
  { id: "pn3", es: "él", de: "er", hint: "Personalpronomen", example: "Él vive en Bogotá.", exampleDe: "Er lebt in Bogotá." },
  { id: "pn4", es: "ella", de: "sie (Einzahl)", hint: "Personalpronomen", example: "Ella trabaja mucho.", exampleDe: "Sie arbeitet viel." },
  { id: "pn5", es: "usted", de: "Sie (formell, Einzahl)", hint: "Personalpronomen", example: "¿Cómo está usted?", exampleDe: "Wie geht es Ihnen?" },
  { id: "pn6", es: "nosotros", de: "wir", hint: "Personalpronomen", example: "Nosotros vivimos aquí.", exampleDe: "Wir leben hier." },
  { id: "pn7", es: "vosotros", de: "ihr", hint: "Personalpronomen (v.a. Spanien; Lateinamerika: ustedes)", example: "Vosotros sois de España.", exampleDe: "Ihr seid aus Spanien." },
  { id: "pn8", es: "ellos", de: "sie (m., Plural)", hint: "Personalpronomen", example: "Ellos llegan tarde.", exampleDe: "Sie kommen spät an." },
  { id: "pn9", es: "ellas", de: "sie (f., Plural)", hint: "Personalpronomen", example: "Ellas son hermanas.", exampleDe: "Sie sind Schwestern." },
  { id: "pn10", es: "ustedes", de: "Sie (Plural) / ihr", hint: "Personalpronomen (formell; in Lateinamerika auch informell)", example: "Ustedes son bienvenidos.", exampleDe: "Sie sind willkommen." },
  { id: "pp1", es: "a", de: "zu, nach", hint: "Präposition (Richtung)", example: "Voy a la ciudad.", exampleDe: "Ich gehe in die Stadt." },
  { id: "pp2", es: "de", de: "von, aus", hint: "Präposition", example: "Vengo de Alemania.", exampleDe: "Ich komme aus Deutschland." },
  { id: "pp3", es: "en", de: "in, auf", hint: "Präposition", example: "Vivo en Núremberg.", exampleDe: "Ich lebe in Nürnberg." },
  { id: "pp4", es: "con", de: "mit", hint: "Präposition", example: "Voy con mi hermano.", exampleDe: "Ich gehe mit meinem Bruder." },
  { id: "pp5", es: "sin", de: "ohne", hint: "Präposition", example: "Café sin azúcar.", exampleDe: "Kaffee ohne Zucker." },
  { id: "pp6", es: "para", de: "für", hint: "Präposition (Zweck/Empfänger)", example: "Esto es para ti.", exampleDe: "Das ist für dich." },
  { id: "pp7", es: "por", de: "für, durch, wegen", hint: "Präposition (Grund/Weg)", example: "Gracias por tu ayuda.", exampleDe: "Danke für deine Hilfe." },
  { id: "pp8", es: "sobre", de: "über, auf", hint: "Präposition", example: "Hablamos sobre el trabajo.", exampleDe: "Wir sprechen über die Arbeit." },
  { id: "pp9", es: "entre", de: "zwischen", hint: "Präposition", example: "Está entre la casa y la calle.", exampleDe: "Es ist zwischen dem Haus und der Straße." },
  { id: "pp10", es: "hasta", de: "bis", hint: "Präposition", example: "Trabajo hasta las cinco.", exampleDe: "Ich arbeite bis fünf Uhr." },
  { id: "pp11", es: "desde", de: "seit, von … an", hint: "Präposition", example: "Vivo aquí desde 2016.", exampleDe: "Ich lebe seit 2016 hier." },
  { id: "pp12", es: "hacia", de: "Richtung, gegen … hin", hint: "Präposition", example: "Camino hacia la ciudad.", exampleDe: "Ich gehe in Richtung Stadt." },
  { id: "v16", es: "empezar", de: "anfangen", hint: "regelmäßig", ipaEs: "/empeˈsar/", ipaDe: "/ˈanfaŋən/", example: "Vamos a empezar la clase.", exampleDe: "Wir fangen die Stunde an." },
  { id: "v17", es: "terminar", de: "beenden", hint: "regelmäßig", ipaEs: "/teɾmiˈnar/", ipaDe: "/bəˈʔɛndən/", example: "Necesito terminar este informe.", exampleDe: "Ich muss diesen Bericht beenden." },
  { id: "v18", es: "necesitar", de: "brauchen", hint: "regelmäßig", ipaEs: "/nesesiˈtar/", ipaDe: "/ˈbʁaʊxən/", example: "Necesito más tiempo.", exampleDe: "Ich brauche mehr Zeit." },
  { id: "v19", es: "gustar", de: "gefallen", hint: "regelmäßig", ipaEs: "/ɡusˈtar/", ipaDe: "/ɡəˈfalən/", example: "Me gusta este libro.", exampleDe: "Mir gefällt dieses Buch." },
  { id: "v20", es: "pensar", de: "denken", hint: "unregelmäßig", ipaEs: "/penˈsar/", ipaDe: "/ˈdɛŋkən/", example: "Pienso en ti.", exampleDe: "Ich denke an dich." },
  { id: "v21", es: "sentir", de: "fühlen, spüren", hint: "unregelmäßig", ipaEs: "/senˈtir/", ipaDe: "/ˈfyːlən/", example: "Siento un dolor en la espalda.", exampleDe: "Ich spüre einen Schmerz im Rücken." },
  { id: "v22", es: "encontrar", de: "finden", hint: "regelmäßig", ipaEs: "/eŋkonˈtrar/", ipaDe: "/ˈfɪndən/", example: "No puedo encontrar mis llaves.", exampleDe: "Ich kann meine Schlüssel nicht finden." },
  { id: "v23", es: "conocer", de: "kennen", hint: "regelmäßig", ipaEs: "/konoˈser/", ipaDe: "/ˈkɛnən/", example: "Quiero conocer a tu familia.", exampleDe: "Ich möchte deine Familie kennenlernen." },
  { id: "v24", es: "vivir", de: "leben", hint: "regelmäßig", ipaEs: "/biˈβir/", ipaDe: "/ˈleːbən/", example: "Vivo en Núremberg.", exampleDe: "Ich lebe in Nürnberg." },
  { id: "v25", es: "trabajar", de: "arbeiten", hint: "regelmäßig", ipaEs: "/traβaˈxar/", ipaDe: "/ˈaɐbaɪtən/", example: "Trabajo todos los días.", exampleDe: "Ich arbeite jeden Tag." },
  { id: "v26", es: "estudiar", de: "studieren, lernen", hint: "regelmäßig", ipaEs: "/estuˈðjar/", ipaDe: "/ʃtuˈdiːʁən/", example: "Estudio español por las noches.", exampleDe: "Ich lerne abends Spanisch." },
  { id: "v27", es: "comer", de: "essen", hint: "unregelmäßig", ipaEs: "/koˈmer/", ipaDe: "/ˈɛsən/", example: "Vamos a comer juntos.", exampleDe: "Lass uns zusammen essen." },
  { id: "v28", es: "beber", de: "trinken", hint: "regelmäßig", ipaEs: "/beˈβer/", ipaDe: "/ˈtʁɪŋkən/", example: "Bebo mucha agua.", exampleDe: "Ich trinke viel Wasser." },
  { id: "v29", es: "dormir", de: "schlafen", hint: "unregelmäßig", ipaEs: "/dorˈmir/", ipaDe: "/ˈʃlaːfən/", example: "Duermo ocho horas.", exampleDe: "Ich schlafe acht Stunden." },
  { id: "v30", es: "salir", de: "ausgehen, hinausgehen", hint: "regelmäßig", ipaEs: "/saˈlir/", ipaDe: "/ˈaʊsɡeːən/", example: "Vamos a salir esta noche.", exampleDe: "Wir gehen heute Abend aus." },
  { id: "v31", es: "venir", de: "kommen", hint: "regelmäßig", ipaEs: "/beˈnir/", ipaDe: "/ˈkɔmən/", example: "¿Puedes venir mañana?", exampleDe: "Kannst du morgen kommen?" },
  { id: "v32", es: "entrar", de: "eintreten, hineingehen", hint: "regelmäßig", ipaEs: "/enˈtrar/", ipaDe: "/ˈaɪntreːtən/", example: "Podemos entrar por aquí.", exampleDe: "Wir können hier eintreten." },
  { id: "v33", es: "volver", de: "zurückkehren", hint: "unregelmäßig", ipaEs: "/bolˈβer/", ipaDe: "/tsuˈʁʏkkeːʁən/", example: "Vuelvo a casa a las seis.", exampleDe: "Ich komme um sechs nach Hause zurück." },
  { id: "v34", es: "escribir", de: "schreiben", hint: "regelmäßig", ipaEs: "/eskriˈβir/", ipaDe: "/ˈʃʁaɪbən/", example: "Voy a escribir un correo.", exampleDe: "Ich werde eine E-Mail schreiben." },
  { id: "v35", es: "leer", de: "lesen", hint: "regelmäßig", ipaEs: "/leˈer/", ipaDe: "/ˈleːzən/", example: "Me gusta leer por la noche.", exampleDe: "Ich lese gerne abends." },
  { id: "v36", es: "escuchar", de: "hören, zuhören", hint: "regelmäßig", ipaEs: "/eskuˈtʃar/", ipaDe: "/ˈtsuːhøːʁən/", example: "Escucho música todos los días.", exampleDe: "Ich höre jeden Tag Musik." },
  { id: "v37", es: "mirar", de: "schauen", hint: "regelmäßig", ipaEs: "/miˈrar/", ipaDe: "/ˈʃaʊən/", example: "Mira esta foto.", exampleDe: "Schau dir dieses Foto an." },
  { id: "v38", es: "buscar", de: "suchen", hint: "regelmäßig", ipaEs: "/busˈkar/", ipaDe: "/ˈzuːxən/", example: "Estoy buscando trabajo.", exampleDe: "Ich suche Arbeit." },
  { id: "v39", es: "esperar", de: "warten, hoffen", hint: "regelmäßig", ipaEs: "/espeˈrar/", ipaDe: "/ˈvaɐtən/", example: "Espero el autobús.", exampleDe: "Ich warte auf den Bus." },
  { id: "v40", es: "llamar", de: "rufen, anrufen", hint: "regelmäßig", ipaEs: "/ʝaˈmar/", ipaDe: "/ˈanʁuːfən/", example: "Te voy a llamar mañana.", exampleDe: "Ich rufe dich morgen an." },
  { id: "v41", es: "preguntar", de: "fragen", hint: "regelmäßig", ipaEs: "/preɣunˈtar/", ipaDe: "/ˈfʁaːɡən/", example: "¿Puedo preguntarte algo?", exampleDe: "Kann ich dich etwas fragen?" },
  { id: "v42", es: "responder", de: "antworten", hint: "regelmäßig", ipaEs: "/rresponˈder/", ipaDe: "/ˈantvɔɐtən/", example: "No respondió a mi mensaje.", exampleDe: "Er/Sie hat nicht auf meine Nachricht geantwortet." },
  { id: "v43", es: "pagar", de: "bezahlen", hint: "regelmäßig", ipaEs: "/paˈɣar/", ipaDe: "/bəˈtsaːlən/", example: "¿Puedo pagar con tarjeta?", exampleDe: "Kann ich mit Karte bezahlen?" },
  { id: "v44", es: "comprar", de: "kaufen", hint: "regelmäßig", ipaEs: "/komˈprar/", ipaDe: "/ˈkaʊfən/", example: "Necesito comprar pan.", exampleDe: "Ich muss Brot kaufen." },
  { id: "v45", es: "vender", de: "verkaufen", hint: "regelmäßig", ipaEs: "/benˈder/", ipaDe: "/fɛɐˈkaʊfən/", example: "Quiero vender mi bicicleta.", exampleDe: "Ich möchte mein Fahrrad verkaufen." },
  { id: "v46", es: "abrir", de: "öffnen", hint: "unregelmäßig", ipaEs: "/aˈβrir/", ipaDe: "/ˈœfnən/", example: "¿Puedes abrir la ventana?", exampleDe: "Kannst du das Fenster öffnen?" },
  { id: "v47", es: "cerrar", de: "schließen", hint: "unregelmäßig", ipaEs: "/seˈrrar/", ipaDe: "/ˈʃliːsən/", example: "Voy a cerrar la puerta.", exampleDe: "Ich werde die Tür schließen." },
  { id: "v48", es: "jugar", de: "spielen", hint: "unregelmäßig", ipaEs: "/xuˈɣar/", ipaDe: "/ˈʃpiːlən/", example: "Los niños juegan en el parque.", exampleDe: "Die Kinder spielen im Park." },
  { id: "v49", es: "ganar", de: "gewinnen", hint: "regelmäßig", ipaEs: "/ɡaˈnar/", ipaDe: "/ɡəˈvɪnən/", example: "Nuestro equipo va a ganar.", exampleDe: "Unser Team wird gewinnen." },
  { id: "v50", es: "perder", de: "verlieren, verpassen", hint: "unregelmäßig", ipaEs: "/perˈder/", ipaDe: "/fɛɐˈliːʁən/", example: "No quiero perder el tren.", exampleDe: "Ich will den Zug nicht verpassen." },
  { id: "v51", es: "cambiar", de: "ändern, wechseln", hint: "regelmäßig", ipaEs: "/kamˈbjar/", ipaDe: "/ˈɛndɐn/", example: "Quiero cambiar de trabajo.", exampleDe: "Ich möchte den Job wechseln." },
  { id: "v52", es: "seguir", de: "folgen, weitermachen", hint: "unregelmäßig", ipaEs: "/seˈɣir/", ipaDe: "/ˈvaɪtɐmaxən/", example: "Vamos a seguir mañana.", exampleDe: "Wir machen morgen weiter." },
  { id: "v53", es: "parecer", de: "scheinen, aussehen", hint: "regelmäßig", ipaEs: "/pareˈser/", ipaDe: "/ˈʃaɪnən/", example: "Parece una buena idea.", exampleDe: "Das scheint eine gute Idee zu sein." },
  { id: "v54", es: "recordar", de: "sich erinnern", hint: "regelmäßig", ipaEs: "/rrekorˈðar/", ipaDe: "/zɪç ɛɐˈʔɪnɐn/", example: "No recuerdo su nombre.", exampleDe: "Ich erinnere mich nicht an seinen Namen." },
  { id: "v55", es: "olvidar", de: "vergessen", hint: "regelmäßig", ipaEs: "/olβiˈðar/", ipaDe: "/fɛɐˈɡɛsən/", example: "No olvides tu teléfono.", exampleDe: "Vergiss dein Handy nicht." },
  { id: "n16", es: "la gente", de: "die Leute", hint: "weiblich", ipaEs: "/ˈxente/", ipaDe: "/ˈlɔʏtə/", example: "La gente es muy amable aquí.", exampleDe: "Die Leute sind hier sehr freundlich." },
  { id: "n17", es: "la persona", de: "die Person", hint: "weiblich", ipaEs: "/perˈsona/", ipaDe: "/pɛɐˈzoːn/", example: "Es una persona muy amable.", exampleDe: "Er/Sie ist eine sehr freundliche Person." },
  { id: "n18", es: "el niño", de: "das Kind", hint: "männlich", ipaEs: "/ˈniɲo/", ipaDe: "/kɪnt/", example: "El niño juega en el jardín.", exampleDe: "Das Kind spielt im Garten." },
  { id: "n19", es: "el hombre", de: "der Mann", hint: "männlich", ipaEs: "/ˈombre/", ipaDe: "/man/", example: "Ese hombre es mi vecino.", exampleDe: "Dieser Mann ist mein Nachbar." },
  { id: "n20", es: "la mujer", de: "die Frau", hint: "weiblich", ipaEs: "/muˈxer/", ipaDe: "/fʁaʊ/", example: "La mujer trabaja en el hospital.", exampleDe: "Die Frau arbeitet im Krankenhaus." },
  { id: "n21", es: "el año", de: "das Jahr", hint: "männlich", ipaEs: "/ˈaɲo/", ipaDe: "/jaːɐ/", example: "Este año viajo a España.", exampleDe: "Dieses Jahr reise ich nach Spanien." },
  { id: "n22", es: "la semana", de: "die Woche", hint: "weiblich", ipaEs: "/seˈmana/", ipaDe: "/ˈvɔxə/", example: "Trabajo cinco días a la semana.", exampleDe: "Ich arbeite fünf Tage die Woche." },
  { id: "n23", es: "el mes", de: "der Monat", hint: "männlich", ipaEs: "/mes/", ipaDe: "/ˈmoːnat/", example: "El próximo mes viajamos.", exampleDe: "Nächsten Monat reisen wir." },
  { id: "n24", es: "la hora", de: "die Stunde, Uhrzeit", hint: "weiblich", ipaEs: "/ˈora/", ipaDe: "/ˈʃtʊndə/", example: "¿Qué hora es?", exampleDe: "Wie spät ist es?" },
  { id: "n25", es: "el minuto", de: "die Minute", hint: "männlich", ipaEs: "/miˈnuto/", ipaDe: "/miˈnuːtə/", example: "Espera un minuto, por favor.", exampleDe: "Warte eine Minute, bitte." },
  { id: "n26", es: "la noche", de: "die Nacht", hint: "weiblich", ipaEs: "/ˈnotʃe/", ipaDe: "/naxt/", example: "Trabajo por la noche.", exampleDe: "Ich arbeite nachts." },
  { id: "n27", es: "la mañana", de: "der Morgen", hint: "weiblich", ipaEs: "/maˈɲana/", ipaDe: "/ˈmɔɐɡən/", example: "Nos vemos por la mañana.", exampleDe: "Wir sehen uns am Morgen." },
  { id: "n28", es: "la tarde", de: "der Nachmittag", hint: "weiblich", ipaEs: "/ˈtarðe/", ipaDe: "/ˈnaːxmɪtaːk/", example: "Voy a estudiar por la tarde.", exampleDe: "Ich werde am Nachmittag lernen." },
  { id: "n29", es: "el lugar", de: "der Ort", hint: "männlich", ipaEs: "/luˈɣar/", ipaDe: "/ɔɐt/", example: "Es un lugar muy bonito.", exampleDe: "Es ist ein sehr schöner Ort." },
  { id: "n30", es: "el país", de: "das Land", hint: "männlich", ipaEs: "/paˈis/", ipaDe: "/lant/", example: "Colombia es un país hermoso.", exampleDe: "Kolumbien ist ein schönes Land." },
  { id: "n31", es: "la historia", de: "die Geschichte", hint: "weiblich", ipaEs: "/isˈtorja/", ipaDe: "/ɡəˈʃɪçtə/", example: "Me gusta la historia de España.", exampleDe: "Ich mag die Geschichte Spaniens." },
  { id: "n32", es: "el problema", de: "das Problem", hint: "männlich", ipaEs: "/proˈβlema/", ipaDe: "/pʁoˈbleːm/", example: "Tenemos un problema.", exampleDe: "Wir haben ein Problem." },
  { id: "n33", es: "la pregunta", de: "die Frage", hint: "weiblich", ipaEs: "/preˈɣunta/", ipaDe: "/ˈfʁaːɡə/", example: "Tengo una pregunta.", exampleDe: "Ich habe eine Frage." },
  { id: "n34", es: "la idea", de: "die Idee", hint: "weiblich", ipaEs: "/iˈðea/", ipaDe: "/iˈdeː/", example: "Es una buena idea.", exampleDe: "Das ist eine gute Idee." },
  { id: "n35", es: "la manera", de: "die Art, Weise", hint: "weiblich", ipaEs: "/maˈnera/", ipaDe: "/aɐt/", example: "Hay otra manera de hacerlo.", exampleDe: "Es gibt eine andere Art, es zu tun." },
];
